#![allow(
    non_camel_case_types,
    unused,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::double_parens,
    non_snake_case,
    clippy::too_many_arguments
)]
// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.75.3.

use crate::api::*;
use core::panic::UnwindSafe;
use flutter_rust_bridge::*;
use std::ffi::c_void;
use std::sync::Arc;

// Section: imports

// Section: wire functions

fn wire_newPushState_impl(port_: MessagePort) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "newPushState",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || move |task_callback| Ok(newPushState()),
    )
}
fn wire_get_handles_impl(
    port_: MessagePort,
    state: impl Wire2Api<RustOpaque<PushState>> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "get_handles",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_state = state.wire2api();
            move |task_callback| get_handles(api_state)
        },
    )
}
fn wire_validate_targets_impl(
    port_: MessagePort,
    state: impl Wire2Api<RustOpaque<PushState>> + UnwindSafe,
    targets: impl Wire2Api<Vec<String>> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "validate_targets",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_state = state.wire2api();
            let api_targets = targets.wire2api();
            move |task_callback| validate_targets(api_state, api_targets)
        },
    )
}
fn wire_cancel_registration_impl(
    port_: MessagePort,
    state: impl Wire2Api<RustOpaque<PushState>> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "cancel_registration",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_state = state.wire2api();
            move |task_callback| Ok(cancel_registration(api_state))
        },
    )
}
fn wire_get_phase_impl(
    port_: MessagePort,
    state: impl Wire2Api<RustOpaque<PushState>> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "get_phase",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_state = state.wire2api();
            move |task_callback| Ok(get_phase(api_state))
        },
    )
}
fn wire_restore_impl(
    port_: MessagePort,
    curr_state: impl Wire2Api<RustOpaque<PushState>> + UnwindSafe,
    data: impl Wire2Api<String> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "restore",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_curr_state = curr_state.wire2api();
            let api_data = data.wire2api();
            move |task_callback| Ok(restore(api_curr_state, api_data))
        },
    )
}
fn wire_new_push_impl(
    port_: MessagePort,
    state: impl Wire2Api<RustOpaque<PushState>> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "new_push",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_state = state.wire2api();
            move |task_callback| Ok(new_push(api_state))
        },
    )
}
fn wire_try_auth_impl(
    port_: MessagePort,
    state: impl Wire2Api<RustOpaque<PushState>> + UnwindSafe,
    username: impl Wire2Api<String> + UnwindSafe,
    password: impl Wire2Api<String> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "try_auth",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_state = state.wire2api();
            let api_username = username.wire2api();
            let api_password = password.wire2api();
            move |task_callback| try_auth(api_state, api_username, api_password)
        },
    )
}
fn wire_register_ids_impl(
    port_: MessagePort,
    state: impl Wire2Api<RustOpaque<PushState>> + UnwindSafe,
    validation_data: impl Wire2Api<String> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "register_ids",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_state = state.wire2api();
            let api_validation_data = validation_data.wire2api();
            move |task_callback| register_ids(api_state, api_validation_data)
        },
    )
}
fn wire_save_push_impl(
    port_: MessagePort,
    state: impl Wire2Api<RustOpaque<PushState>> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "save_push",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_state = state.wire2api();
            move |task_callback| Ok(save_push(api_state))
        },
    )
}
// Section: wrapper structs

// Section: static checks

// Section: allocate functions

// Section: related functions

// Section: impl Wire2Api

pub trait Wire2Api<T> {
    fn wire2api(self) -> T;
}

impl<T, S> Wire2Api<Option<T>> for *mut S
where
    *mut S: Wire2Api<T>,
{
    fn wire2api(self) -> Option<T> {
        (!self.is_null()).then(|| self.wire2api())
    }
}

impl Wire2Api<u8> for u8 {
    fn wire2api(self) -> u8 {
        self
    }
}

// Section: impl IntoDart

// Section: executor

support::lazy_static! {
    pub static ref FLUTTER_RUST_BRIDGE_HANDLER: support::DefaultHandler = Default::default();
}

#[cfg(not(target_family = "wasm"))]
#[path = "bridge_generated.io.rs"]
mod io;
#[cfg(not(target_family = "wasm"))]
pub use io::*;
